// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-gateway/internal/ent/httprule"
	"go-gateway/internal/ent/predicate"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// HttpRuleQuery is the builder for querying HttpRule entities.
type HttpRuleQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.HttpRule
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (hrq *HttpRuleQuery) Where(ps ...predicate.HttpRule) *HttpRuleQuery {
	hrq.predicates = append(hrq.predicates, ps...)
	return hrq
}

// Limit adds a limit step to the query.
func (hrq *HttpRuleQuery) Limit(limit int) *HttpRuleQuery {
	hrq.limit = &limit
	return hrq
}

// Offset adds an offset step to the query.
func (hrq *HttpRuleQuery) Offset(offset int) *HttpRuleQuery {
	hrq.offset = &offset
	return hrq
}

// Order adds an order step to the query.
func (hrq *HttpRuleQuery) Order(o ...OrderFunc) *HttpRuleQuery {
	hrq.order = append(hrq.order, o...)
	return hrq
}

// First returns the first HttpRule entity in the query. Returns *NotFoundError when no httprule was found.
func (hrq *HttpRuleQuery) First(ctx context.Context) (*HttpRule, error) {
	nodes, err := hrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{httprule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hrq *HttpRuleQuery) FirstX(ctx context.Context) *HttpRule {
	node, err := hrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HttpRule id in the query. Returns *NotFoundError when no id was found.
func (hrq *HttpRuleQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = hrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{httprule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hrq *HttpRuleQuery) FirstIDX(ctx context.Context) int64 {
	id, err := hrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only HttpRule entity in the query, returns an error if not exactly one entity was returned.
func (hrq *HttpRuleQuery) Only(ctx context.Context) (*HttpRule, error) {
	nodes, err := hrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{httprule.Label}
	default:
		return nil, &NotSingularError{httprule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hrq *HttpRuleQuery) OnlyX(ctx context.Context) *HttpRule {
	node, err := hrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only HttpRule id in the query, returns an error if not exactly one id was returned.
func (hrq *HttpRuleQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = hrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = &NotSingularError{httprule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hrq *HttpRuleQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := hrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HttpRules.
func (hrq *HttpRuleQuery) All(ctx context.Context) ([]*HttpRule, error) {
	if err := hrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return hrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (hrq *HttpRuleQuery) AllX(ctx context.Context) []*HttpRule {
	nodes, err := hrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HttpRule ids.
func (hrq *HttpRuleQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := hrq.Select(httprule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hrq *HttpRuleQuery) IDsX(ctx context.Context) []int64 {
	ids, err := hrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hrq *HttpRuleQuery) Count(ctx context.Context) (int, error) {
	if err := hrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return hrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (hrq *HttpRuleQuery) CountX(ctx context.Context) int {
	count, err := hrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hrq *HttpRuleQuery) Exist(ctx context.Context) (bool, error) {
	if err := hrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return hrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (hrq *HttpRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := hrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hrq *HttpRuleQuery) Clone() *HttpRuleQuery {
	if hrq == nil {
		return nil
	}
	return &HttpRuleQuery{
		config:     hrq.config,
		limit:      hrq.limit,
		offset:     hrq.offset,
		order:      append([]OrderFunc{}, hrq.order...),
		unique:     append([]string{}, hrq.unique...),
		predicates: append([]predicate.HttpRule{}, hrq.predicates...),
		// clone intermediate query.
		sql:  hrq.sql.Clone(),
		path: hrq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ServiceID int64 `json:"service_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HttpRule.Query().
//		GroupBy(httprule.FieldServiceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (hrq *HttpRuleQuery) GroupBy(field string, fields ...string) *HttpRuleGroupBy {
	group := &HttpRuleGroupBy{config: hrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := hrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return hrq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		ServiceID int64 `json:"service_id,omitempty"`
//	}
//
//	client.HttpRule.Query().
//		Select(httprule.FieldServiceID).
//		Scan(ctx, &v)
//
func (hrq *HttpRuleQuery) Select(field string, fields ...string) *HttpRuleSelect {
	selector := &HttpRuleSelect{config: hrq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := hrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return hrq.sqlQuery(), nil
	}
	return selector
}

func (hrq *HttpRuleQuery) prepareQuery(ctx context.Context) error {
	if hrq.path != nil {
		prev, err := hrq.path(ctx)
		if err != nil {
			return err
		}
		hrq.sql = prev
	}
	return nil
}

func (hrq *HttpRuleQuery) sqlAll(ctx context.Context) ([]*HttpRule, error) {
	var (
		nodes = []*HttpRule{}
		_spec = hrq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &HttpRule{config: hrq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, hrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (hrq *HttpRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hrq.querySpec()
	return sqlgraph.CountNodes(ctx, hrq.driver, _spec)
}

func (hrq *HttpRuleQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := hrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (hrq *HttpRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   httprule.Table,
			Columns: httprule.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: httprule.FieldID,
			},
		},
		From:   hrq.sql,
		Unique: true,
	}
	if ps := hrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, httprule.ValidColumn)
			}
		}
	}
	return _spec
}

func (hrq *HttpRuleQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(hrq.driver.Dialect())
	t1 := builder.Table(httprule.Table)
	selector := builder.Select(t1.Columns(httprule.Columns...)...).From(t1)
	if hrq.sql != nil {
		selector = hrq.sql
		selector.Select(selector.Columns(httprule.Columns...)...)
	}
	for _, p := range hrq.predicates {
		p(selector)
	}
	for _, p := range hrq.order {
		p(selector, httprule.ValidColumn)
	}
	if offset := hrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HttpRuleGroupBy is the builder for group-by HttpRule entities.
type HttpRuleGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hrgb *HttpRuleGroupBy) Aggregate(fns ...AggregateFunc) *HttpRuleGroupBy {
	hrgb.fns = append(hrgb.fns, fns...)
	return hrgb
}

// Scan applies the group-by query and scan the result into the given value.
func (hrgb *HttpRuleGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := hrgb.path(ctx)
	if err != nil {
		return err
	}
	hrgb.sql = query
	return hrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := hrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HttpRuleGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) StringsX(ctx context.Context) []string {
	v, err := hrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = hrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) StringX(ctx context.Context) string {
	v, err := hrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HttpRuleGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) IntsX(ctx context.Context) []int {
	v, err := hrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = hrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) IntX(ctx context.Context) int {
	v, err := hrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HttpRuleGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := hrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = hrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) Float64X(ctx context.Context) float64 {
	v, err := hrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HttpRuleGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := hrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (hrgb *HttpRuleGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = hrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (hrgb *HttpRuleGroupBy) BoolX(ctx context.Context) bool {
	v, err := hrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (hrgb *HttpRuleGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range hrgb.fields {
		if !httprule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := hrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (hrgb *HttpRuleGroupBy) sqlQuery() *sql.Selector {
	selector := hrgb.sql
	columns := make([]string, 0, len(hrgb.fields)+len(hrgb.fns))
	columns = append(columns, hrgb.fields...)
	for _, fn := range hrgb.fns {
		columns = append(columns, fn(selector, httprule.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(hrgb.fields...)
}

// HttpRuleSelect is the builder for select fields of HttpRule entities.
type HttpRuleSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (hrs *HttpRuleSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := hrs.path(ctx)
	if err != nil {
		return err
	}
	hrs.sql = query
	return hrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (hrs *HttpRuleSelect) ScanX(ctx context.Context, v interface{}) {
	if err := hrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) Strings(ctx context.Context) ([]string, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HttpRuleSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (hrs *HttpRuleSelect) StringsX(ctx context.Context) []string {
	v, err := hrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = hrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (hrs *HttpRuleSelect) StringX(ctx context.Context) string {
	v, err := hrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) Ints(ctx context.Context) ([]int, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HttpRuleSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (hrs *HttpRuleSelect) IntsX(ctx context.Context) []int {
	v, err := hrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = hrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (hrs *HttpRuleSelect) IntX(ctx context.Context) int {
	v, err := hrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HttpRuleSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (hrs *HttpRuleSelect) Float64sX(ctx context.Context) []float64 {
	v, err := hrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = hrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (hrs *HttpRuleSelect) Float64X(ctx context.Context) float64 {
	v, err := hrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HttpRuleSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (hrs *HttpRuleSelect) BoolsX(ctx context.Context) []bool {
	v, err := hrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (hrs *HttpRuleSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = hrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = fmt.Errorf("ent: HttpRuleSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (hrs *HttpRuleSelect) BoolX(ctx context.Context) bool {
	v, err := hrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (hrs *HttpRuleSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range hrs.fields {
		if !httprule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := hrs.sqlQuery().Query()
	if err := hrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (hrs *HttpRuleSelect) sqlQuery() sql.Querier {
	selector := hrs.sql
	selector.Select(selector.Columns(hrs.fields...)...)
	return selector
}
