// Code generated by entc, DO NOT EDIT.

package tcprule

const (
	// Label holds the string label denoting the tcprule type in the database.
	Label = "tcp_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceID holds the string denoting the service_id field in the database.
	FieldServiceID = "service_id"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"

	// Table holds the table name of the tcprule in the database.
	Table = "tcp_rules"
)

// Columns holds all SQL columns for tcprule fields.
var Columns = []string{
	FieldID,
	FieldServiceID,
	FieldPort,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
