// Code generated by entc, DO NOT EDIT.

package httprule

const (
	// Label holds the string label denoting the httprule type in the database.
	Label = "http_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceID holds the string denoting the service_id field in the database.
	FieldServiceID = "service_id"
	// FieldRuleType holds the string denoting the rule_type field in the database.
	FieldRuleType = "rule_type"
	// FieldRule holds the string denoting the rule field in the database.
	FieldRule = "rule"
	// FieldNeedHTTPS holds the string denoting the need_https field in the database.
	FieldNeedHTTPS = "need_https"
	// FieldNeedWebsocket holds the string denoting the need_websocket field in the database.
	FieldNeedWebsocket = "need_websocket"
	// FieldNeedStripURI holds the string denoting the need_strip_uri field in the database.
	FieldNeedStripURI = "need_strip_uri"
	// FieldURLRewrite holds the string denoting the url_rewrite field in the database.
	FieldURLRewrite = "url_rewrite"
	// FieldHeaderTransfor holds the string denoting the header_transfor field in the database.
	FieldHeaderTransfor = "header_transfor"

	// Table holds the table name of the httprule in the database.
	Table = "http_rules"
)

// Columns holds all SQL columns for httprule fields.
var Columns = []string{
	FieldID,
	FieldServiceID,
	FieldRuleType,
	FieldRule,
	FieldNeedHTTPS,
	FieldNeedWebsocket,
	FieldNeedStripURI,
	FieldURLRewrite,
	FieldHeaderTransfor,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
