// Code generated by entc, DO NOT EDIT.

package accesscontrol

const (
	// Label holds the string label denoting the accesscontrol type in the database.
	Label = "access_control"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceID holds the string denoting the service_id field in the database.
	FieldServiceID = "service_id"
	// FieldOpenAuth holds the string denoting the open_auth field in the database.
	FieldOpenAuth = "open_auth"
	// FieldBlackList holds the string denoting the black_list field in the database.
	FieldBlackList = "black_list"
	// FieldWhiteList holds the string denoting the white_list field in the database.
	FieldWhiteList = "white_list"
	// FieldWhiteHostName holds the string denoting the white_host_name field in the database.
	FieldWhiteHostName = "white_host_name"
	// FieldClientipFlowLimit holds the string denoting the clientip_flow_limit field in the database.
	FieldClientipFlowLimit = "clientip_flow_limit"
	// FieldServiceFlowLimit holds the string denoting the service_flow_limit field in the database.
	FieldServiceFlowLimit = "service_flow_limit"

	// Table holds the table name of the accesscontrol in the database.
	Table = "access_controls"
)

// Columns holds all SQL columns for accesscontrol fields.
var Columns = []string{
	FieldID,
	FieldServiceID,
	FieldOpenAuth,
	FieldBlackList,
	FieldWhiteList,
	FieldWhiteHostName,
	FieldClientipFlowLimit,
	FieldServiceFlowLimit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
