server:
  address: localhost:8000
  readtimeout: 10
  writetimeout: 10
  maxheaderbytes: 10
  allowip:
    - 127.0.0.1
    - 127.0.0.1
database:
  drivername: mysql
  datasourcename: root:123456@tcp(127.0.0.1:3306)/ent?charset=utf8
redis:
  proxylist:
    - 127.0.0.1:6789
    - 127.0.0.1:6780
    - 127.0.0.1:6781
  password:
  db:
  conntimeout: 10
  readtimeout: 10
  writetimeout: 10
log:
  level: 1