// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-gateway/ent/service"
	"strings"
	"time"

	"github.com/facebook/ent/dialect/sql"
)

// Service is the model entity for the Service schema.
type Service struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// LoadType holds the value of the "load_type" field.
	LoadType int `json:"load_type,omitempty"`
	// ServiceName holds the value of the "service_name" field.
	ServiceName string `json:"service_name,omitempty"`
	// ServiceDesc holds the value of the "service_desc" field.
	ServiceDesc string `json:"service_desc,omitempty"`
	// CreateAt holds the value of the "create_at" field.
	CreateAt time.Time `json:"create_at,omitempty"`
	// UpdateAt holds the value of the "update_at" field.
	UpdateAt time.Time `json:"update_at,omitempty"`
	// IsDelete holds the value of the "is_delete" field.
	IsDelete int8 `json:"is_delete,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Service) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullInt64{},  // load_type
		&sql.NullString{}, // service_name
		&sql.NullString{}, // service_desc
		&sql.NullTime{},   // create_at
		&sql.NullTime{},   // update_at
		&sql.NullInt64{},  // is_delete
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Service fields.
func (s *Service) assignValues(values ...interface{}) error {
	if m, n := len(values), len(service.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int64(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field load_type", values[0])
	} else if value.Valid {
		s.LoadType = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field service_name", values[1])
	} else if value.Valid {
		s.ServiceName = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field service_desc", values[2])
	} else if value.Valid {
		s.ServiceDesc = value.String
	}
	if value, ok := values[3].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field create_at", values[3])
	} else if value.Valid {
		s.CreateAt = value.Time
	}
	if value, ok := values[4].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field update_at", values[4])
	} else if value.Valid {
		s.UpdateAt = value.Time
	}
	if value, ok := values[5].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field is_delete", values[5])
	} else if value.Valid {
		s.IsDelete = int8(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this Service.
// Note that, you need to call Service.Unwrap() before calling this method, if this Service
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Service) Update() *ServiceUpdateOne {
	return (&ServiceClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Service) Unwrap() *Service {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Service is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Service) String() string {
	var builder strings.Builder
	builder.WriteString("Service(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", load_type=")
	builder.WriteString(fmt.Sprintf("%v", s.LoadType))
	builder.WriteString(", service_name=")
	builder.WriteString(s.ServiceName)
	builder.WriteString(", service_desc=")
	builder.WriteString(s.ServiceDesc)
	builder.WriteString(", create_at=")
	builder.WriteString(s.CreateAt.Format(time.ANSIC))
	builder.WriteString(", update_at=")
	builder.WriteString(s.UpdateAt.Format(time.ANSIC))
	builder.WriteString(", is_delete=")
	builder.WriteString(fmt.Sprintf("%v", s.IsDelete))
	builder.WriteByte(')')
	return builder.String()
}

// Services is a parsable slice of Service.
type Services []*Service

func (s Services) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
