// Code generated by entc, DO NOT EDIT.

package grpcrule

const (
	// Label holds the string label denoting the grpcrule type in the database.
	Label = "grpc_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceID holds the string denoting the service_id field in the database.
	FieldServiceID = "service_id"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldHeaderTransfor holds the string denoting the header_transfor field in the database.
	FieldHeaderTransfor = "header_transfor"

	// Table holds the table name of the grpcrule in the database.
	Table = "grpc_rules"
)

// Columns holds all SQL columns for grpcrule fields.
var Columns = []string{
	FieldID,
	FieldServiceID,
	FieldPort,
	FieldHeaderTransfor,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
