// Code generated by entc, DO NOT EDIT.

package tenant

const (
	// Label holds the string label denoting the tenant type in the database.
	Label = "tenant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSecret holds the string denoting the secret field in the database.
	FieldSecret = "secret"
	// FieldWhiteIps holds the string denoting the white_ips field in the database.
	FieldWhiteIps = "white_ips"
	// FieldQpd holds the string denoting the qpd field in the database.
	FieldQpd = "qpd"
	// FieldQPS holds the string denoting the qps field in the database.
	FieldQPS = "qps"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldIsDelete holds the string denoting the is_delete field in the database.
	FieldIsDelete = "is_delete"

	// Table holds the table name of the tenant in the database.
	Table = "tenants"
)

// Columns holds all SQL columns for tenant fields.
var Columns = []string{
	FieldID,
	FieldAppID,
	FieldName,
	FieldSecret,
	FieldWhiteIps,
	FieldQpd,
	FieldQPS,
	FieldCreateAt,
	FieldUpdateAt,
	FieldIsDelete,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
